#!/usr/bin/env bash
# Creates a PID file, handles signals
echo $$ > /tmp/myscript.pid

trap "echo 'I hate the kill command'" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm -f /tmp/myscript.pid; exit" SIGQUIT

while true
do
    echo "To infinity and beyond"
    sleep 2
done
