#!/bin/bash

echo $$ > /tmp/my_script.pid

trap "echo 'I hate the kill command'" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm /tmp/my_script.pid; exit" SIGQUIT SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
